name: Build

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      HEROKU_APP_NAME:
        required: true
        type: string

jobs:
  docker_image:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3

      - name: Log
        run: echo "app name ${{ secrets.HEROKU_APP_NAME }}"
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.HEROKU_APP_NAME }}:$(date +%s)
