name: CD - Production

on:
  push:
    branches: ['master']

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  build:
    needs: ci
    uses: ./.github/workflows/build.yml
    with:
      environment: Production
    secrets:
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      environment: Production
    secrets:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
