name: CD - Staging

on:
  pull_request:
    branches: ['master']

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    with:
      environment: Staging
    secrets:
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

  # TO DO : refresh stage db with data matching current production

  deploy:
    needs: ci
    uses: ./.github/workflows/cd.yml
    with:
      environment: Staging
    secrets:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
