name: CI - Production

on:
  pull_request:
    branches: ['master']

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  build:
    uses: ./.github/workflows/build.yml
    with:
      environment: Production
    secrets:
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
