name: CI - Production

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    with:
      app_name: cicd-test-app

  build:
    uses: ./.github/workflows/build.yml
    with:
      app_name: cicd-test-app
