name: CI - Production

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  build:
    uses: ./.github/workflows/build.yml
    with:
      # TO DO : pull app name from secret?
      app_name: cicd-test-app

  # TO DO : move to different workflow
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      app_name: cicd-test-app
