name: CI

on:
  push:
    branches: ['github-actions']
#     branches: ['master']
#             pull_request:
#     branches: ['master']

env:
  APP_NAME: cicd-test-app

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci
        # run: npm ci --ignore-scripts

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: npm run

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $APP_NAME:$(date +%s)
